Repository Momentree-Project/Backend, pull requests merged in 2025-05, with the labels that each got.

#23 feat: #3 소셜 로그인 회원가입
  build.gradle.kts
  src/main/java/com/momentree/domain/auth/controller/AuthController.java
  src/main/java/com/momentree/domain/auth/entity/AuthToken.java
  src/main/java/com/momentree/domain/auth/jwt/AccessTokenProvider.java
  src/main/java/com/momentree/domain/auth/jwt/JwtFilter.java
  src/main/java/com/momentree/domain/auth/jwt/RefreshTokenGenerator.java
  src/main/java/com/momentree/domain/auth/jwt/RefreshTokenProvider.java
  src/main/java/com/momentree/domain/auth/jwt/TokenProperty.java
  src/main/java/com/momentree/domain/auth/oauth2/CustomOAuth2User.java
  src/main/java/com/momentree/domain/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/momentree/domain/auth/oauth2/OAuth2UserInfo.java
  src/main/java/com/momentree/domain/auth/repository/AuthTokenRepository.java
  src/main/java/com/momentree/domain/auth/response/AccessTokenResponseDto.java
  src/main/java/com/momentree/domain/auth/service/AuthService.java
  src/main/java/com/momentree/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/momentree/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/momentree/domain/user/UserCodeManager.java
  src/main/java/com/momentree/domain/user/entity/User.java
  src/main/java/com/momentree/domain/user/repository/UserRepository.java
  src/main/java/com/momentree/global/config/SecurityConfig.java
  src/main/java/com/momentree/global/entity/BaseEntity.java
  src/main/java/com/momentree/global/utils/UrlUtils.java
Labels: Feature ✨

#26 feat: #24 jwt 클레임 추가 및 user 추가정보 저장, 커플 연결
  src/main/java/com/momentree/domain/auth/controller/AuthController.java
  src/main/java/com/momentree/domain/auth/dto/response/AccessTokenResponseDto.java
  src/main/java/com/momentree/domain/auth/jwt/AccessTokenProvider.java
  src/main/java/com/momentree/domain/auth/oauth2/CustomOAuth2User.java
  src/main/java/com/momentree/domain/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/momentree/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/momentree/domain/couple/controller/CoupleController.java
  src/main/java/com/momentree/domain/couple/dto/request/CoupleConnectRequestDto.java
  src/main/java/com/momentree/domain/couple/dto/response/CoupleConnectResponseDto.java
  src/main/java/com/momentree/domain/couple/entity/Couple.java
  src/main/java/com/momentree/domain/couple/repository/CoupleRepository.java
  src/main/java/com/momentree/domain/couple/service/CoupleService.java
  src/main/java/com/momentree/domain/couple/service/impl/CoupleServiceImpl.java
  src/main/java/com/momentree/domain/user/controller/UserController.java
  src/main/java/com/momentree/domain/user/dto/request/UserAdditionalInfoRequestDto.java
  src/main/java/com/momentree/domain/user/dto/response/UserAdditionalInfoResponseDto.java
  src/main/java/com/momentree/domain/user/entity/User.java
  src/main/java/com/momentree/domain/user/repository/UserRepository.java
  src/main/java/com/momentree/domain/user/service/UserService.java
  src/main/java/com/momentree/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
Labels: Feature ✨

#27 feat: #25 커플 스케줄 기능 CRUD 추가
  src/main/java/com/momentree/domain/category/repository/CategoryRepository.java
  src/main/java/com/momentree/domain/couple/entity/Schedule.java
  src/main/java/com/momentree/domain/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/momentree/domain/schedule/entity/Schedule.java
  src/main/java/com/momentree/domain/schedule/entity/ScheduleReminder.java
  src/main/java/com/momentree/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/momentree/domain/schedule/request/CreateScheduleRequestDto.java
  src/main/java/com/momentree/domain/schedule/request/UpdateScheduleRequestDto.java
  src/main/java/com/momentree/domain/schedule/response/DetailScheduleResponseDto.java
  src/main/java/com/momentree/domain/schedule/response/ScheduleResponseDto.java
  src/main/java/com/momentree/domain/schedule/service/ScheduleService.java
  src/main/java/com/momentree/domain/schedule/service/impl/ScheduleServiceImpl.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
  src/main/java/com/momentree/global/utils/UrlUtils.java
Labels: Feature ✨

#29 bug: #28 소셜 로그인 후 access 토큰 body 반환 방식을 redirect후 api요청으로 수정
  src/main/java/com/momentree/domain/auth/controller/AuthController.java
  src/main/java/com/momentree/domain/auth/dto/response/AccessTokenResponseDto.java
  src/main/java/com/momentree/domain/auth/dto/response/AccessTokenWithUserResponseDto.java
  src/main/java/com/momentree/domain/auth/jwt/AccessTokenProvider.java
  src/main/java/com/momentree/domain/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/momentree/domain/auth/service/AuthService.java
  src/main/java/com/momentree/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/momentree/domain/couple/service/impl/CoupleServiceImpl.java
Labels: Bug 🐞

#30 fix: #28 반환하는 User 정보에 birth 추가 및 marketingConsent 로직 변경
  src/main/java/com/momentree/domain/auth/dto/response/AccessTokenWithUserResponseDto.java
  src/main/java/com/momentree/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/momentree/domain/user/entity/User.java
Labels: Bug 🐞

#31 fix: #28 토큰 검증 실패 시 401 에러 반환
  src/main/java/com/momentree/domain/auth/jwt/JwtFilter.java
Labels: Bug 🐞

#34 feat: 스케줄 카테고리 CRUD 추가
  src/main/java/com/momentree/domain/category/controller/ApiV1CategoryController.java
  src/main/java/com/momentree/domain/category/entity/Category.java
  src/main/java/com/momentree/domain/category/repository/CategoryRepository.java
  src/main/java/com/momentree/domain/category/request/PatchScheduleCategoryRequestDto.java
  src/main/java/com/momentree/domain/category/request/PostScheduleCategoryRequestDto.java
  src/main/java/com/momentree/domain/category/response/ScheduleCategoryResponseDto.java
  src/main/java/com/momentree/domain/category/service/CategoryService.java
  src/main/java/com/momentree/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/momentree/domain/couple/validator/CoupleValidator.java
  src/main/java/com/momentree/domain/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/momentree/domain/schedule/entity/Schedule.java
  src/main/java/com/momentree/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/momentree/domain/schedule/request/PatchScheduleRequestDto.java
  src/main/java/com/momentree/domain/schedule/request/PostScheduleRequestDto.java
  src/main/java/com/momentree/domain/schedule/request/UpdateScheduleRequestDto.java
  src/main/java/com/momentree/domain/schedule/response/GetAllScheduleResponseDto.java
  src/main/java/com/momentree/domain/schedule/response/GetScheduleResponseDto.java
  src/main/java/com/momentree/domain/schedule/service/ScheduleService.java
  src/main/java/com/momentree/domain/schedule/service/impl/ScheduleServiceImpl.java
Labels: Feature ✨

#35 feat: #32 마이페이지 기능 개발
  src/main/java/com/momentree/domain/auth/controller/ApiV1AuthController.java
  src/main/java/com/momentree/domain/auth/dto/response/AccessTokenWithUserResponseDto.java
  src/main/java/com/momentree/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/momentree/domain/couple/controller/ApiV1CoupleController.java
  src/main/java/com/momentree/domain/couple/dto/request/PatchCoupleStartedDayRequestDto.java
  src/main/java/com/momentree/domain/couple/dto/response/CoupleConnectResponseDto.java
  src/main/java/com/momentree/domain/couple/dto/response/CoupleDisconnectResponseDto.java
  src/main/java/com/momentree/domain/couple/dto/response/PatchCoupleStartedDayResponseDto.java
  src/main/java/com/momentree/domain/couple/entity/Couple.java
  src/main/java/com/momentree/domain/couple/service/CoupleService.java
  src/main/java/com/momentree/domain/couple/service/impl/CoupleServiceImpl.java
  src/main/java/com/momentree/domain/user/controller/ApiV1UserController.java
  src/main/java/com/momentree/domain/user/controller/UserController.java
  src/main/java/com/momentree/domain/user/dto/request/PatchMarketingConsentRequestDto.java
  src/main/java/com/momentree/domain/user/dto/request/PatchPersonalRequestDto.java
  src/main/java/com/momentree/domain/user/dto/request/PatchProfileRequestDto.java
  src/main/java/com/momentree/domain/user/dto/response/GetProfileResponseDto.java
  src/main/java/com/momentree/domain/user/dto/response/PatchMarketingConsentResponseDto.java
  src/main/java/com/momentree/domain/user/dto/response/PatchPersonalResponseDto.java
  src/main/java/com/momentree/domain/user/dto/response/PatchProfileResponseDto.java
  src/main/java/com/momentree/domain/user/entity/User.java
  src/main/java/com/momentree/domain/user/repository/UserRepository.java
  src/main/java/com/momentree/domain/user/service/UserService.java
  src/main/java/com/momentree/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
Labels: Feature ✨, Refactor 🔨

#37 feat: #36 AWS S3 기반 프로필 이미지 업로드/삭제 기능 개발
  build.gradle.kts
  src/main/java/com/momentree/domain/image/entity/Image.java
  src/main/java/com/momentree/domain/image/repository/ImageRepository.java
  src/main/java/com/momentree/domain/user/controller/ApiV1UserController.java
  src/main/java/com/momentree/domain/user/dto/response/GetProfileResponseDto.java
  src/main/java/com/momentree/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/momentree/global/config/S3Config.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
  src/main/java/com/momentree/global/service/S3Service.java
  src/main/java/com/momentree/global/service/impl/S3ServiceImpl.java
  src/main/java/com/momentree/global/utils/FileUtil.java
Labels: Feature ✨

#40 feat: #38 회원 탈퇴시 이메일 전송 기능 구현
  build.gradle.kts
  src/main/java/com/momentree/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/momentree/global/config/EmailConfig.java
  src/main/java/com/momentree/global/config/property/EmailProperty.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
  src/main/java/com/momentree/global/service/EmailService.java
  src/main/java/com/momentree/global/service/impl/EmailServiceImpl.java
  src/main/resources/templates/Withdrawal-email.html
Labels: Feature ✨

#42 feat: #41 POST 도메인 CRUD
  src/main/java/com/momentree/domain/category/controller/ApiV1CategoryController.java
  src/main/java/com/momentree/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/momentree/domain/post/post/controller/ApiV1PostController.java
  src/main/java/com/momentree/domain/post/post/dto/request/PostRequestDto.java
  src/main/java/com/momentree/domain/post/post/dto/response/PatchPostRequestDto.java
  src/main/java/com/momentree/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/momentree/domain/post/post/entity/Post.java
  src/main/java/com/momentree/domain/post/post/repository/PostRepository.java
  src/main/java/com/momentree/domain/post/post/service/Impl/PostServiceImpl.java
  src/main/java/com/momentree/domain/post/post/service/PostService.java
  src/main/java/com/momentree/domain/schedule/controller/ApiV1ScheduleController.java
  src/main/java/com/momentree/domain/schedule/service/impl/ScheduleServiceImpl.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
  src/main/java/com/momentree/global/validator/UserValidator.java
Labels: Feature ✨

#44 feat: #41 PostResponseDto에서 User 엔티티 대신 UserResponseDto를 반환하도록 수정
  src/main/java/com/momentree/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/momentree/domain/post/post/service/Impl/PostServiceImpl.java
  src/main/java/com/momentree/domain/user/dto/response/UserInfoResponseDto.java
Labels: Refactor 🔨

#45 feat: #41 게시판 개발
  src/main/java/com/momentree/domain/image/entity/Image.java
  src/main/java/com/momentree/domain/image/repository/ImageRepository.java
  src/main/java/com/momentree/domain/post/like/dto/response/GetPostLikesResponse.java
  src/main/java/com/momentree/domain/post/like/entity/Likes.java
  src/main/java/com/momentree/domain/post/like/repository/LikeRepository.java
  src/main/java/com/momentree/domain/post/like/service/LikeService.java
  src/main/java/com/momentree/domain/post/like/service/impl/LikeServiceImpl.java
  src/main/java/com/momentree/domain/post/post/controller/ApiV1PostController.java
  src/main/java/com/momentree/domain/post/post/dto/request/PostRequestDto.java
  src/main/java/com/momentree/domain/post/post/dto/response/PatchPostRequestDto.java
  src/main/java/com/momentree/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/momentree/domain/post/post/entity/Post.java
  src/main/java/com/momentree/domain/post/post/service/Impl/PostServiceImpl.java
  src/main/java/com/momentree/domain/user/controller/ApiV1UserController.java
  src/main/java/com/momentree/global/constant/FileType.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
  src/main/java/com/momentree/global/service/S3Service.java
  src/main/java/com/momentree/global/service/impl/S3ServiceImpl.java
  src/main/java/com/momentree/global/strategy/FileNameStrategy.java
  src/main/java/com/momentree/global/strategy/PostFileNameStrategy.java
  src/main/java/com/momentree/global/strategy/ProfileFileNameStrategy.java
Labels: Feature ✨

#47 feat: 배포 도메인 Security 설정 추가
  src/main/java/com/momentree/global/config/SecurityConfig.java
Labels: Feature ✨

#48 feat: 배포 도메인 Security 설정 추가
  src/main/java/com/momentree/global/config/SecurityConfig.java
Labels: Feature ✨

#49 feat: 배포 도메인 CORS 허용 추가
  src/main/java/com/momentree/global/config/SecurityConfig.java
Labels: Feature ✨

#53 feat: favicon.ico 추가
  src/main/resources/static/favicon.ico
Labels: Feature ✨

#56 fix: OAuth2 로그인을 위한 prod 환경 설정 수정
  src/main/resources/application-prod.yml
Labels: Feature ✨

#59 fix: Spring Security OAuth2 경로 허용 설정 추가
  src/main/java/com/momentree/global/config/SecurityConfig.java
  src/main/java/com/momentree/global/utils/UrlUtils.java
Labels: Bug 🐞

#66 fix: 임시로 Security 완전 비활성화
  src/main/java/com/momentree/MomentreeApplication.java
Labels: Bug 🐞

#78 feat: #41 댓글/대댓글 기능 추가
  src/main/java/com/momentree/domain/image/entity/Image.java
  src/main/java/com/momentree/domain/post/comment/controller/ApiV1CommentController.java
  src/main/java/com/momentree/domain/post/comment/dto/request/PatchCommentRequest.java
  src/main/java/com/momentree/domain/post/comment/dto/request/PostCommentRequest.java
  src/main/java/com/momentree/domain/post/comment/dto/response/PostCommentResponse.java
  src/main/java/com/momentree/domain/post/comment/entity/Comment.java
  src/main/java/com/momentree/domain/post/comment/repository/CommentRepository.java
  src/main/java/com/momentree/domain/post/comment/service/CommentService.java
  src/main/java/com/momentree/domain/post/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/momentree/domain/post/like/entity/Likes.java
  src/main/java/com/momentree/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/momentree/domain/post/post/service/Impl/PostServiceImpl.java
  src/main/java/com/momentree/global/exception/ErrorCode.java
Labels: Feature ✨
